apiVersion: v1
kind: Secret
metadata:
  name: u-nbreport
type: Opaque
data:
  # Each secret value must be base64 encoded.
  # e.g. `echo -n hello | base64 | pbcopy`
  keeper_password: FIXME
  redis_url: FIXME
  aws_id: FIXME
  aws_secret: FIXME
